---
# role: ansible-role-test
# file: .travis.yml

os: linux
dist: focal

language: python

services: docker

branches:
  only:
    - main

cache:
  pip: true
  directories:
  - ".tox"

env:
  global:
    - TOX_PARALLEL_NO_SPINNER=1
  matrix:
    - TOX_IMG="Alpine"    TOX_ANSIBLE="{29,210,40}"
    - TOX_IMG="Amazon"    TOX_ANSIBLE="{29,210,40}"
    - TOX_IMG="Arch"      TOX_ANSIBLE="{29,210,40}"
    - TOX_IMG="CentOS"    TOX_ANSIBLE="{29,210,40}"
    - TOX_IMG="Debian"    TOX_ANSIBLE="{29,210,40}"
    - TOX_IMG="Fedora"    TOX_ANSIBLE="{29,210,40}"
    - TOX_IMG="OpenSuse"  TOX_ANSIBLE="{29,210,40}"
    - TOX_IMG="Oracle"    TOX_ANSIBLE="{29,210,40}"
    - TOX_IMG="Ubuntu"    TOX_ANSIBLE="{29,210,40}"

before_install:
  - python -m pip install --upgrade pip

install:
  - pip install tox-travis

script:
  - tox -e $(echo py${TRAVIS_PYTHON_VERSION} | tr -d .)-an${TOX_ANSIBLE}-${TOX_IMG} -p 2 -o true
