---
# role: ansible-role-test
# file: requirements.yml

collections:
  - freeipa.ansible_freeipa

roles: []

# - src: https://github.com/jam82/ansible-role-baseline.git
#   name: baseline
#   version: main
