---
# role: ansible-role-test
# file: tasks/main.yml

- name: "Tasks for ansible-role-test"
  when: test_role_enabled | bool
  block:
    - name: "Set distribution dependent variables"
      ansible.builtin.include_vars: "{{ item }}"
      vars:
        params:
          files:
            - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
            - "{{ ansible_distribution }}.yml"
            - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
            - "{{ ansible_os_family }}.yml"
          paths:
            - 'vars'
          skip: true
      loop: "{{ query('first_found', params, errors='ignore') }}"
    - name: "Install packages for ansible-role-test"
      ansible.builtin.package:
        name: "{{ test_packages }}"
        state: present
