---
# name: jam82.ansible-role-test
# file: molecule/default/molecule.yml

# Note on command and entrypoint = ~ ... :/ WTF???
# Using the pre-built container defaults, when nothing is specified would be
# straight forward ... not some sleep infinite shell command.

dependency:
  name: galaxy
  requirements-file: meta/requirements.yml
  role-file: meta/requirements.yml
driver:
  name: podman
lint: set -e; ansible-lint
platforms:
  - command: null
    entrypoint: null
    image: docker.io/${uns:-jam82}/molecule-${img:-fedora}:${tag:-latest}
    name: test
    pre_build_image: true
provisioner:
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      interpreter_python: auto_silent
      timer: null
      yaml: null
    ssh_connection:
      pipelining: true
  log: true
  name: ansible
  playbooks:
    converge: create.yml
    verify: verify.yml
scenario:
  name: default
verifier:
  name: ansible
